name: Publish Python 🐍 distribution 📦 to PyPI

on:
  release:
    types:
      - published

jobs:
  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/docx_merge
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: 🧾 Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: 📦 Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: 🏷️ Get tag version and set project version
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          echo "TAG_VERSION: $TAG_VERSION"
          if [ -z "$TAG_VERSION" ]; then
            echo "No tag version found. Exiting."
            exit 1
          fi
          echo "Setting version to $TAG_VERSION"
          poetry version "$TAG_VERSION"

      - name: 📦 Install dependencies
        run: poetry install --without dev

      - name: 🏗️ Build and Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          echo "Publishing to PyPI..."
          poetry config repositories.pypi https://upload.pypi.org/legacy/
          poetry config http-basic.pypi __token__ $PYPI_TOKEN
          poetry publish --build --repository pypi
